#!/bin/bash

if [ ! -f "/var/appliance/.applianceSetupDone" ]; then
	active=0
	for i in $(ip link | sed -e :a -e '$!N;s/\n[[:blank:]]/ /;ta' -e 'P;D' | grep -w 'BROADCAST' | awk -F ': ' '{print $2}'); do
		if grep -q "^    ${i}:" /etc/netplan/01-netcfg.yaml 2>/dev/null || grep -q "iface ${i} inet" /etc/network/interfaces 2>/dev/null; then
			active=1
		fi
	done
	if [ ${active} -eq 0 ]; then
		iface=$(ip link | sed -e :a -e '$!N;s/\n[[:blank:]]/ /;ta' -e 'P;D' | grep -w 'BROADCAST' | head -1 | awk -F ': ' '{print $2}')
		if [ -f "/etc/netplan/01-netcfg.yaml" ]; then
			cfg=$(grep -m 1 "^    [a-z]" /etc/netplan/01-netcfg.yaml | sed -e 's/[[:space:]]//g' -e 's/://g')
			if [ "${cfg}" != "${iface}" ]; then
				sed -i "s/${cfg}/${iface}/g" /etc/netplan/01-netcfg.yaml
				netplan apply
			fi
		elif [ -f "/etc/network/interfaces" ]; then
			cfg=$(grep 'iface' /etc/network/interfaces | grep -v loopback | head -1 | awk '{print $2}')
			if [ "${cfg}" != "${iface}" ]; then
				sed -i "s/${cfg}/${iface}/g" /etc/network/interfaces
				service networking restart
			fi
		fi
	fi
	touch /var/appliance/.applianceSetupDone
	sed -i '/applianceFirstRun/d' /etc/rc.local
	rm -f "${0}"
fi

exit 0